/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./pages/AboutMe.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Education: typeof import('./pages/Education.vue')['default']
    Experience: typeof import('./pages/Experience.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Profile: typeof import('./pages/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./pages/Skills.vue')['default']
  }
}
